version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digi-portal  
    container_name: digi-portal
    restart: unless-stopped
    ports:
      - "8010:80"
    volumes:
      - .:/var/www

networks:
  laravel:
    driver: bridge
